### PR TITLE
Compatibility with psr/container 2.0

### PR DESCRIPTION
**Pull request by jbboehr**
## Description

Provides compatibility with psr/container v2.0

## Motivation and context

This will allow tukio to be used alongside libraries that require psr/container 2.0, and me to test v2.0 of [my PHP extension](https://github.com/jbboehr/php-psr) against your repo.

## How has this been tested?

The `config` and `require-dev` sections in `composer.json` as-is prevent testing psr/container v2.0. I removed those sections (except for phpunit) and ran the unit tests manually (after running `composer update`) on PHP 7.3 and PHP 8.0.

If my understanding is correct, CI will not test the library with psr/container 2.0 due the the presence of the `config` section and `nunomaduro/phpinsights`

I looked into submitting a similar patch to `nunomaduro/phpinsights` but the same issue exists in some of their dependencies, and that's about as far down the rabbit hole as I want to go right now.

I would personally probably not merge this as-is without either a new release from or removing `nunomaduro/phpinsights`, or maybe installing it globally in CI if it is an executable.

Once the above issue is resolved, there could be a new PHP 8.0 build added in CI with `composer update --prefer-lowest` to test v1 of psr/container on PHP 8.0 (I believe this is what this does).

## Checklist:

- [x] I have read the **[CONTRIBUTING](CONTRIBUTING.md)** document.
- [x] My pull request addresses exactly one patch/feature.
- [x] I have created a branch for this patch/feature.
- [x] Each individual commit in the pull request is meaningful.
- [ ] I have added tests to cover my changes.
- [x] If my change requires a change to the documentation, I have updated it accordingly.

### CODE REVIEW

**Comment by jbboehr** [comment]
Looks like `nunomaduro/phpinsights` depends on `symfony` which won't support v2.0 of container until symfony 6.0 due to BC break.

**Comment by Crell** [comment]
Hm.  @nunomaduro, can you comment here on the best way to proceed?

**Comment by nunomaduro** [comment]
@Crell Consider this: https://github.com/bamarni/composer-bin-plugin.

**Comment by Crell** [comment]
Well, this is odd.  Trying that plugin, I get the following error from composer-bin-plugin:

> Package nunomaduro/phpinsights has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version 

Which... is wrong, as the 1.14 version of phpinsights looks like it has all the right requirements in it.  And it does install fine when I put it in the normal require-dev block.

**Comment by jbboehr** [comment]
I believe my latest commit is the proper way to use the composer-bin plugin, if I am not mistaken.

**Comment by Crell** [comment]
I think this all works?  It's the first time I've seen vendor-bin so I'm not 100% sure it's setup right. :smile: 

The `--prefer-lowest` test is getting the lowest version of all dependencies, so I'm not sure if that's ideal, but at least it doesn't seem to break any tests.  So...  YOLO, I guess.

`composer.lock` has no business being committed, but that appears to have been my error from a previous merge.  So, I'm going to merge this, then remove the lock file separately.  I'm going to do a bit more cleanup then first as well before I tag a new release, since I guess I should actually act on some of of the stuff that insights found, now that I actually run it...

Thanks, @jbboehr!

**Pull request merged**
