### PR TITLE
Add support for PHP 8.1, and remove support for 7.2 and 7.3

### PR DESCRIPTION
**Pull request by martinssipenko**
## Description

Add support for PHP 8.1, and remove support for PHP 7.2 and 7.3.

Dropping 7.2 support is the easiest way to upgrade to PHPUnit 9.5 which supports `>=7.3` and also `8.1`. Older version of PHPUnit 8.x does [access the $GLOBALS which is no longer supported in PHP 8.1](https://php.watch/versions/8.1/GLOBALS-restrictions).

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

Please, please, please, don't send your pull request until all of the boxes are ticked. Once your pull request is created, it will trigger a build on our [continuous integration](http://www.phptherightway.com/#continuous-integration) server to make sure your [tests and code style pass](https://help.github.com/articles/about-required-status-checks/).

- [x] I have read the **[CONTRIBUTING](CONTRIBUTING.md)** document.
- [x] My pull request addresses exactly one patch/feature.
- [x] I have created a branch for this patch/feature.
- [X] Each individual commit in the pull request is meaningful.
- [ ] I have added tests to cover my changes.
- [ ] If my change requires a change to the documentation, I have updated it accordingly.

If you're unsure about any of these, don't hesitate to ask. We're here to help!

### CODE REVIEW

**Comment by Crell** [comment]
Urk.  Dagnabbit, PHPUnit.

I am a bit torn here. Dropping an old version should arguably be a major release; however, I had been intending to use the next major release to clean up the API some and bump the required version all the way to 8.0, as the pre/post named arguments API feels somewhat different (and I like the potential of 8.0 to have a unified API rather than quite so many methods).  But that's a much larger task than just getting PHPUnit to run.

Thoughts, since I presume you're using this library in production, and thus I want to break as little as possible on you? :smile:

**Comment by martinssipenko** [comment]
Also torn, but given I personally still need to support 7.4 I'd vote for keeping it. Also, I'm not 100% sure that dropping an older PHP version requires a new major. Those that use this package on 7.2 would still be able to as composer would take care of installing the version that works on their platform, but they would not get updates after the next minor. If we check [composer stats](https://packagist.org/packages/crell/tukio/php-stats#1.3) then there are 0% of 7.2 users that install this packages `1.3.x` version (that is if interpret the stats correctly).

**Comment by Crell** [comment]
Hm, it looks from the stats like we could go all the way to 7.4.  Though I've no idea what's going on with that 8.1 bump that dies out... :sweat_smile: 

The stats give me more confidence, so let's do this: Please update this PR to go all the way to requiring 7.4, as there seem to be no older users at this point anyway.  I can merge and tag that later today or tomorrow.  Then we'll see about a 2.x for 8.0 that cleans up the API in some way and leans into 8.0 functionality.  (Feedback on what works and doesn't in your case would be welcome for that.  File a separate feedback issue.  Thanks.)

**Comment by martinssipenko** [comment]
@Crell Updated the PR with changes requested.

**Comment by Crell** [comment]
Thanks.  I have a little tidying up to do while I'm here, then I'll release a new minor later today.

**Comment by Crell** [comment]
Resolves #18

**Pull request merged**
